Controllers/AdminController.cs
using FirstApp.Data;
using FirstApp.Models;
using FirstApp.Models.Admin;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace FirstApp.Controllers
{ [Authorize]
    public class AdminController : Controller
    {    
        private readonly EmployeeDBContext employeeDBContext;

        public AdminController(EmployeeDBContext employeeDBContext)
        {
            this.employeeDBContext = employeeDBContext;
            }
        
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var empolyees = await employeeDBContext.Employees.ToListAsync();
            return View(empolyees);
        }
         [HttpGet]
       public async Task<IActionResult> showRequests()
        {
            var requests = await employeeDBContext.Requests.ToListAsync();
            return View(requests);
        }
      
       
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddEmployeeViewModel addEmployeeRequest)
        {
            if (ModelState.IsValid)
            {
                var employee = new Employee()
            {
                EmployeeId = Guid.NewGuid(), 
                Name = addEmployeeRequest.Name,
                EmailId = addEmployeeRequest.Email,
                userPassword=addEmployeeRequest.userPassword,
                Department = addEmployeeRequest.Department,
                DateOfBirth = addEmployeeRequest.DateOfBirth,  
            };

            await employeeDBContext.Employees.AddAsync(employee);
            await employeeDBContext.SaveChangesAsync();
            return RedirectToAction("Index");
            }
              return View();         
        }
        
        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var employee = await employeeDBContext.Employees.FirstOrDefaultAsync(x => x.EmployeeId == id);

            if(employee != null)
            {
                var viewModel = new UpdateEmployeeViewModel()
                {
                    Id = employee.EmployeeId, 
                    Name = employee.Name,
                    Email = employee.EmailId,
                    userPassword = employee.userPassword,
                    Department = employee.Department,
                    DateOfBirth = employee.DateOfBirth,
                };
                return await Task.Run(() => View("View", viewModel));
            }

            return View(employee); 
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateEmployeeViewModel model)
        { 
            if (ModelState.IsValid)
            {
                var employee = await employeeDBContext.Employees.FindAsync(model.Id);

            if (employee != null)
            { 
                employee.Name = model.Name;
                employee.EmailId = model.Email;
                employee.userPassword = model.userPassword;
                employee.DateOfBirth = model.DateOfBirth;
                employee.Department = model.Department;

                await employeeDBContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
                
            }
            return View();
            
        }

        public async Task<IActionResult> Delete(UpdateEmployeeViewModel model)
        {
            var employee = await employeeDBContext.Employees.FindAsync(model.Id);  

            if (employee != null)
            {
                employeeDBContext.Employees.Remove(employee);

                await employeeDBContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
           return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> showHistory()
        {
            var empolyees = await employeeDBContext.BookingHistories.ToListAsync();
            return View(empolyees);
        }
        
    }
} 

Controllers/DashboardController.cs
// Title       :Online Bus Booking System
//  Author     :Abinash(IFET)
// Created at  :01-03-2023
// Updated at  :13-03-2023
// Reviewed by :
// Reviewed at :

using Microsoft.AspNetCore.Mvc;
using FirstApp.Models;
using Microsoft.AspNetCore.Authorization;
using FirstApp.Data;
using Microsoft.EntityFrameworkCore;


namespace FirstApp.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {

        private readonly EmployeeDBContext employeeDBContext;

        public DashboardController(EmployeeDBContext employeeDBContext)
        {
            this.employeeDBContext = employeeDBContext;
        }
        [HttpGet]
        public async Task<IActionResult> displayHistory()
        {
            var empolyees = await employeeDBContext.BookingHistories.Where(b => b.UserId == CurrentUser.UserId).ToListAsync();
            return View(empolyees);
        }



        public IActionResult Index(Employee employee)
        {
            try
            {
                HttpContext.Session.SetString("UserName", CurrentUser.display(employee.EmailId));
                return View();
            }
            catch (Exception)
            {
                return View();
            }
        }

        public async Task<IActionResult> showProfile()
        {
            var empolyees = await employeeDBContext.Employees.Where(b => b.EmployeeId == CurrentUser.UserId).ToListAsync();
            return View(empolyees);
        }

        [HttpGet]
        public ActionResult bookRide()
        {
            return View();
        }

        [HttpPost]
        public ActionResult bookRide(CurrentUser currentUser)
        {

            string? status = CurrentUser.bookBus(currentUser.Destination, currentUser.Date);
            if (status == "Success")
            {
                string? to = TempData["mail"].ToString();
                string notification = CurrentUser.sendNotification(to, currentUser);

                return RedirectToAction("seatBooked", currentUser);
            }
            else if (status == "Leave")
            {

                ModelState.AddModelError(nameof(BookingHistory.Date), "Please Select  Working Days");
                return View();
            }
            else if (status == "No-Destination")
            {
                ViewBag.message = "Please Select Available Destinations";
                return View();
            }

            ModelState.AddModelError(nameof(BookingHistory.Date), "Please Select Upcomming Days");
            return View();
        }

        // [HttpGet]
        public ActionResult seatBooked()
        {
            return View();
        }


        public ActionResult contact()
        {
            return View();
        }

        [HttpGet]
        public ActionResult sendRequest()
        {
            return View();
        }

        [HttpPost]
        public ActionResult sendRequest(Request request)
        {
            if (ModelState.IsValid)
            {
                CurrentUser.sendRequest(request.Message);
                return RedirectToAction("Index");
            }
            return View();
        }


    }
}

Views/Admin/Add.cshtml
@* Title       :Online Bus Booking System
Author      :Abinash(IFET)
Created at  :01-03-2023
Updated at  :13-03-2023
Reviewed by :
Reviewed at : *@
@model FirstApp.Models.Admin.AddEmployeeViewModel

@{
    Layout=null;
}



@using Microsoft.AspNetCore.Http

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bus Booking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstApp.styles.css" asp-append-version="true" />
</head>
<body style="margin-bottom: 50px;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3 navbar-red" >
            <div class="container-fluid" >
                @if (User.Identity.IsAuthenticated)
                {
                  <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index">
                    <img style="width:60px;" src="~/images/bus logo1.png" alt="LOGO">
                </a>
                   
                }
                else
                {
                      <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                    <img style="width:60px;" src="~/images/bus logo1.png" alt="LOGO">
                </a>
                }
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" >
                    <ul class="navbar-nav flex-grow-1">
                         @if(User.Identity.IsAuthenticated){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="map"><b>Map</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index"><b>Employees</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Add"><b>Add Employees</b></a>
                        </li>
                         }
                        </ul>
                        <div>
                            <ul class="navbar-nav flex-grow-1">
                                
                        @if(User.Identity.IsAuthenticated){
                             @* <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Dashboard" asp-action="Index">
                                  <img style="width:20px;" src="~/images/notification.png" alt="notification">
                </a>
                        </li> *@
                            
                            <li class="nav-item">
                            <a class="nav-link text-dark "  style="text-align:right;" asp-controller="Home" asp-action="logOut"><b>Logout</b></a>
                        </li>
                        }
                        else{
                            <li class="nav-item">
                            <a class="nav-link text-dark "  style="text-align:right;" asp-controller="Employee" asp-action="login"><b>Login</b></a>
                        </li>
                        }
                            </ul>
                           
                        </div>
                </div>
            </div>
        </nav>
    </header>

	<link rel="stylesheet" href="~/css/login.css" type="text/css" />

	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-10 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
		      	<h3 class="text-center mb-4">ADD EMPLOYEE</h3>
						<form method="post">
		      		<div class="form-group">
                        <label for="Name" style="color: #855AA6;">Name</label>
		      			<input type="text"asp-for="Name" class="form-control rounded-left" placeholder="Enter Your Name" required>
						@Html.ValidationMessageFor(model=>model.Name,"",new {@class="error"})
						<div asp-validation-for="Name"></div>
		      		</div>

                    <div class="form-group">
                        <label for="Name" style="color: #855AA6;">E-mail</label>
		      			<input type="email"asp-for="Email" class="form-control rounded-left" placeholder="Enter Your Email-ID" required>
						@Html.ValidationMessageFor(model=>model.Email,"",new {@class="error"})
						<div asp-validation-for="Email"></div>
		      		</div>

                    <div class="form-group">
                        <label for="Name" style="color: #855AA6;">Password</label>
		      			<input type="text"asp-for="userPassword" class="form-control rounded-left" placeholder="Enter Your Password" required>
						@Html.ValidationMessageFor(model=>model.userPassword,"",new {@class="error"})
						<div asp-validation-for="userPassword"></div>
		      		</div>
                    <div class="form-group">
                        <label for="Name" style="color: #855AA6;">Date Of Birth</label>
		      			<input type="date"asp-for="DateOfBirth" class="form-control rounded-left" placeholder="Enter Your Date Of Birth" required>
						@Html.ValidationMessageFor(model=>model.DateOfBirth,"",new {@class="error"})
						<div asp-validation-for="DateOfBirth"></div>
		      		</div>

                    <div class="form-group">
                        <label for="Name" style="color: #855AA6;">Department</label>
		      			<input type="text"asp-for="Department" class="form-control rounded-left" placeholder="Enter Your Department" required>
						@Html.ValidationMessageFor(model=>model.Department,"",new {@class="error"})
						<div asp-validation-for="Department"></div>
		      		</div>
	            <div class="form-group">
	            	<button type="submit" asp-controller="Admin" asp-action="Add" class="btn btn-primary rounded submit p-3 px-5">submit</button>
	            </div>
	          </form>  
	        </div>
		</div>

			</div>
			
		</div>
		
	</section>
	<script src="js/jquery.min.js"></script>
  <script src="js/popper.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/main.js"></script>
</body>

Views/Admin/Index.cshtml
@model List<FirstApp.Models.Employee> 
@{
    Layout=null;
}


@using Microsoft.AspNetCore.Http
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bus Booking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstApp.styles.css" asp-append-version="true" />
</head>
<body style="margin-bottom: 50px;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3 navbar-red" >
            <div class="container-fluid" >
                @if (User.Identity.IsAuthenticated)
                {
                  <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index">
                    <img style="width:60px;" src="~/images/bus logo1.png" alt="LOGO">
                </a>
                   
                }
                else
                {
                      <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                    <img style="width:60px;" src="~/images/bus logo1.png" alt="LOGO">
                </a>
                }
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" >
                    <ul class="navbar-nav flex-grow-1">
                         @if(User.Identity.IsAuthenticated){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="map"><b>Map</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index"><b>Employees</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Add"><b>Add Employees</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="showHistory"><b>History</b></a>
                        </li>
                         }
                        </ul>
                        <div>
                            <ul class="navbar-nav flex-grow-1">
                                
                        @if(User.Identity.IsAuthenticated){
                             <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="showRequests">
                                  <img style="width:20px;" src="~/images/notification.png" alt="notification">
                </a>
                        </li>
                            
                            <li class="nav-item">
                            <a class="nav-link text-dark "  style="text-align:right;" asp-controller="Home" asp-action="logOut"><b>Logout</b></a>
                        </li>
                        }
                        else{
                            <li class="nav-item">
                            <a class="nav-link text-dark "  style="text-align:right;" asp-controller="Employee" asp-action="login"><b>Login</b></a>
                        </li>
                        }
                            </ul>
                           
                        </div>
                </div>
            </div>
        </nav>
    </header>
</body>


<h3 style="text-align: center;">Employees</h3>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Password</th>
            <th>Date Of Birth</th>
            <th>Department</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model) {
            <tr>
                <td>@employee.EmployeeId</td>
                <td>@employee.Name</td>
                <td>@employee.EmailId</td>
                <td>@employee.userPassword</td>
                <td>@employee.DateOfBirth.ToString("dd-MM-yyyy")</td>
                <td>@employee.Department</td>
                <td><a href="Admin/View/@employee.EmployeeId">View</a></td>      
            </tr>
        }
    </tbody>
</table>

Views/Admin/View.cshtml
@model FirstApp.Models.Admin.UpdateEmployeeViewModel
@{
    Layout=null;
}



@using Microsoft.AspNetCore.Http
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bus Booking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstApp.styles.css" asp-append-version="true" />
</head>
<body style="margin-bottom: 50px;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3 navbar-red" >
            <div class="container-fluid" >
                @if (User.Identity.IsAuthenticated)
                {
                  <a class="nav-link" asp-area="" asp-controller="Dashboard" asp-action="Index">
                    <img style="width:60px;" src="~/images/bus logo1.png" alt="LOGO">
                </a>
                   
                }
                else
                {
                      <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                    <img style="width:60px;" src="~/images/bus logo1.png" alt="LOGO">
                </a>
                }
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" >
                    <ul class="navbar-nav flex-grow-1">
                         @if(User.Identity.IsAuthenticated){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="map"><b>Map</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index"><b>Employees</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Add"><b>Add Employees</b></a>
                        </li>
                         }
                        </ul>
                        <div>
                            <ul class="navbar-nav flex-grow-1">
                                
                        @if(User.Identity.IsAuthenticated){
                             @* <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Dashboard" asp-action="Index">
                                  <img style="width:20px;" src="~/images/notification.png" alt="notification">
                </a>
                        </li> *@
                            
                            <li class="nav-item">
                            <a class="nav-link text-dark "  style="text-align:right;" asp-controller="Home" asp-action="logOut"><b>Logout</b></a>
                        </li>
                        }
                        else{
                            <li class="nav-item">
                            <a class="nav-link text-dark "  style="text-align:right;" asp-controller="Employee" asp-action="login"><b>Login</b></a>
                        </li>
                        }
                            </ul>
                           
                        </div>
                </div>
            </div>
        </nav>
    </header>


<link rel="stylesheet" href="~/css/login.css" type="text/css" />

	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-10 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
		      	<h3 class="text-center mb-4">ADD EMPLOYEE</h3>
						<form method="post">
                    <div class="form-group">
                        <label for="Name" style="color: #855AA6;">Id</label>
		      			<input type="text"asp-for="Id" class="form-control rounded-left" placeholder="Id" readonly>
						@Html.ValidationMessageFor(model=>model.Id,"",new {@class="error"})
						<div asp-validation-for="Id"></div>
		      		</div>



		      		<div class="form-group">
                        <label for="Name" style="color: #855AA6;">Name</label>
		      			<input type="text"asp-for="Name" class="form-control rounded-left" placeholder="Enter Your Name" required>
						@Html.ValidationMessageFor(model=>model.Name,"",new {@class="error"})
						<div asp-validation-for="Name"></div>
		      		</div>

                    <div class="form-group">
                        <label for="Name" style="color: #855AA6;"><E-mail></E-mail></label>
		      			<input type="email"asp-for="Email" class="form-control rounded-left" placeholder="Enter Your Email-ID" required>
						@Html.ValidationMessageFor(model=>model.Email,"",new {@class="error"})
						<div asp-validation-for="Email"></div>
		      		</div>

                    <div class="form-group">
                        <label for="Name" style="color: #855AA6;">Password</label>
		      			<input type="text"asp-for="userPassword" class="form-control rounded-left" placeholder="Enter Your Password" required>
						@Html.ValidationMessageFor(model=>model.userPassword,"",new {@class="error"})
						<div asp-validation-for="userPassword"></div>
		      		</div>
                    <div class="form-group">
                        <label for="Name" style="color: #855AA6;">Date Of Birth</label>
		      			<input type="date"asp-for="DateOfBirth" class="form-control rounded-left" placeholder="Enter Your Date Of Birth" required>
						@Html.ValidationMessageFor(model=>model.DateOfBirth,"",new {@class="error"})
						<div asp-validation-for="DateOfBirth"></div>
		      		</div>

                    <div class="form-group">
                        <label for="Name" style="color: #855AA6;">Department</label>
		      			<input type="text"asp-for="Department" class="form-control rounded-left" placeholder="Enter Your Department" required>
						@Html.ValidationMessageFor(model=>model.Department,"",new {@class="error"})
						<div asp-validation-for="Department"></div>
		      		</div>


	            <div class="form-group">
	<button type="submit" class="btn btn-primary">Save Update</button>
    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Admin">Delete</button>
	            </div>
	          </form>  
	        </div>
		</div>

			</div>
			
		</div>
		
	</section>
	<script src="js/jquery.min.js"></script>
  <script src="js/popper.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/main.js"></script>
</body>

Views/Admin/showHistory.cshtml
@model List<FirstApp.Models.BookingHistory> 
@{
    Layout=null;
}


@using Microsoft.AspNetCore.Http
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bus Booking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstApp.styles.css" asp-append-version="true" />
</head>
<body style="margin-bottom: 50px;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3 navbar-red" >
            <div class="container-fluid" >
                @if (User.Identity.IsAuthenticated)
                {
                  <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index">
                    <img style="width:60px;" src="~/images/bus logo1.png" alt="LOGO">
                </a>
                   
                }
                else
                {
                      <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                    <img style="width:60px;" src="~/images/bus logo1.png" alt="LOGO">
                </a>
                }
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" >
                    <ul class="navbar-nav flex-grow-1">
                         @if(User.Identity.IsAuthenticated){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="map"><b>Map</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index"><b>Employees</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Add"><b>Add Employees</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="showHistory"><b>History</b></a>
                        </li>
                         }
                        </ul>
                        <div>
                            <ul class="navbar-nav flex-grow-1">
                                
                        @if(User.Identity.IsAuthenticated){
                             @* <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Dashboard" asp-action="Index">
                                  <img style="width:20px;" src="~/images/notification.png" alt="notification">
                </a>
                        </li> *@
                            
                            <li class="nav-item">
                            <a class="nav-link text-dark "  style="text-align:right;" asp-controller="Home" asp-action="logOut"><b>Logout</b></a>
                        </li>
                        }
                        else{
                            <li class="nav-item">
                            <a class="nav-link text-dark "  style="text-align:right;" asp-controller="Employee" asp-action="login"><b>Login</b></a>
                        </li>
                        }
                            </ul>
                           
                        </div>
                </div>
            </div>
        </nav>
    </header>
</body>


<h3 style="text-align: center;">History</h3>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Destination</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model) {
            <tr>
                <td>@employee.UserId</td>
                <td>@employee.Name</td> 
                <td>@employee.Date</td>     
                <td>@employee.Destination</td> 
            </tr>
        }
    </tbody>
</table>